-- ============================================
-- SISTEMA HOSPITAL TALAGANTE - IMAGENOLOGIA
-- Base de Datos PostgreSQL
-- ============================================

-- Extensiones
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ============================================
-- TABLA: usuarios
-- ============================================
CREATE TABLE usuarios (
    id SERIAL PRIMARY KEY,
    rut VARCHAR(12) UNIQUE NOT NULL,
    nombre VARCHAR(150) NOT NULL,
    email VARCHAR(150) UNIQUE NOT NULL,
    celular VARCHAR(20),
    password_hash VARCHAR(255) NOT NULL,
    rol VARCHAR(20) NOT NULL CHECK (rol IN ('ingresador', 'administrador')),
    activo BOOLEAN DEFAULT true,
    debe_cambiar_password BOOLEAN DEFAULT true,
    ultimo_login TIMESTAMP NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_usuarios_rut ON usuarios(rut);
CREATE INDEX idx_usuarios_email ON usuarios(email);

-- ============================================
-- TABLA: pacientes
-- ============================================
CREATE TABLE pacientes (
    id SERIAL PRIMARY KEY,
    rut VARCHAR(12) UNIQUE NOT NULL,
    tipo_identificacion VARCHAR(20) NOT NULL DEFAULT 'RUT_CHILENO',
    nombre_completo VARCHAR(200) NOT NULL,
    fecha_nacimiento DATE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_pacientes_rut ON pacientes(rut);
CREATE INDEX idx_pacientes_nombre ON pacientes(nombre_completo);

-- ============================================
-- CATALOGOS
-- ============================================

-- Previsiones
CREATE TABLE previsiones (
    id SERIAL PRIMARY KEY,
    nombre VARCHAR(50) UNIQUE NOT NULL,
    activo BOOLEAN DEFAULT true
);

INSERT INTO previsiones (nombre) VALUES
('FONASA A'),
('FONASA B'),
('FONASA C'),
('FONASA D'),
('ACCIDENTE ESCOLAR'),
('ACCIDENTE LABORAL'),
('ACCIDENTE TRÁNSITO'),
('CAPREDENA'),
('DIPRECA'),
('ISAPRE'),
('PARTICULAR'),
('PRAIS'),
('PREVISIÓN PROVISORIA'),
('SIN PREVISIÓN');

-- Procedencias
CREATE TABLE procedencias (
    id SERIAL PRIMARY KEY,
    nombre VARCHAR(100) UNIQUE NOT NULL,
    activo BOOLEAN DEFAULT true
);

INSERT INTO procedencias (nombre) VALUES 
('CARDIOLOGÍA'),
('CIRUGÍA'),
('CMA'),
('CONSULTORIO ISLA DE MAIPO'),
('CUIDADOS PALEATIVOS'),
('DERMATOLOGÍA'),
('GERIATRÍA'),
('GES'),
('HOSPITAL DE MELIPILLA'),
('HOSPITAL DE PEÑAFLOR'),
('HOSPITAL SAN JUAN DE DIOS'),
('HOSPITALIZACIÓN DOMICILIARIA'),
('IMAGENOLOGÍA'),
('MEDICINA'),
('MEDICINA FÍSICA Y REHABILITACÍON'),
('MEDICINA TACO'),
('NEFROLOGÍA'),
('NEONATOLOGÍA'),
('NEUROLOGÍA'),
('OBSTETRICIA Y GINECOLOGÍA'),
('OTORRINOLARINGOLOGÍA'),
('PABELLÓN'),
('PEDIATRÍA'),
('PRAIS'),
('PSQUIATRÍA'),
('TRAUMATOLOGÍA Y ORTOPEDIA'),
('UCI'),
('UCM'),
('URGENCIA ADULTO'),
('URGENCIA GINECO-OBSTÉTRICA'),
('URGENCIA PEDIÁTRICA'),
('UROLOGÍA'),
('UTI');

-- Codigos MAI (por tipo de examen)
CREATE TABLE codigos_mai (
    id SERIAL PRIMARY KEY,
    tipo_examen VARCHAR(10) NOT NULL CHECK (tipo_examen IN ('TAC', 'RX', 'ECO')),
    codigo VARCHAR(20) NOT NULL,
    descripcion TEXT NOT NULL,
    activo BOOLEAN DEFAULT true,
    UNIQUE(tipo_examen, codigo)
);

CREATE INDEX idx_codigos_tipo ON codigos_mai(tipo_examen);

INSERT INTO codigos_mai (tipo_examen, codigo, descripcion) VALUES 
('TAC', '403001', 'TAC DE CRÁNEO ENCEFÁLICA'),
('TAC', '403002', 'TAC DE HIPOTÁLAMO-HIPÓFISIS'),
('TAC', '403003', 'TAC DE FOSA POSTERIOR'),
('TAC', '403006', 'TAC DE TEMPORAL-OÍDO'),
('TAC', '403007', 'TAC DE ÓRBITAS MAXILOFACIAL'),
('TAC', '403008', 'TAC DE COLUMNA CERVICAL'),
('TAC', '403012', 'TAC DE CUELLO, PARTES BLANDAS'),
('TAC', '403013', 'TAC DE TÓRAX'),
('TAC', '403014', 'TAC DE ABDOMEN'),
('TAC', '403016', 'TAC DE PELVIS'),
('TAC', '403017', 'TAC MUSCULOESQUELÉTICA POR ZONA ANATÓMICA'),
('TAC', '403018', 'TAC DE COLUMNA DORSAL'),
('TAC', '403019', 'TAC DE COLUMNA LUMBAR'),
('TAC', '403020', 'TAC DE ABDOMEN Y PELVIS'),
('TAC', '403021', 'TAC PIELOGRAFÍA'),
('TAC', '403022', 'TAC UROGRAFÍA'),
('TAC', '403023', 'TAC DE COLONOSCOPÍA VIRTUAL'),
('TAC', '403024', 'TAC PLANIFICACIÓN RADIOTERAPIA'),
('TAC', '403025', 'TAC DE CALCIO CORONARIO'),
('TAC', '403026', 'TAC DE ENTEROGRAFIA'),
('TAC', '403101', 'ANGIOTAC DE ENCÉFALO'),
('TAC', '403102', 'ANGIOTAC DE TÓRAX'),
('TAC', '403103', 'ANGIOTAC DE ABDOMEN'),
('TAC', '403104', 'ANGIOTAC DE CUELLO'),
('TAC', '403105', 'ANGIOTAC DE PELVIS'),
('TAC', '403106', 'ANGIOTAC CARDÍACO'),
('TAC', '403107', 'ANGIOTAC DE EXTREMIDADES INFERIORES (BILATERAL)'),
('TAC', '403108', 'ANGIOTAC DE EXTREMIDAD SUPERIOR (UNILATERAL)'),

('RX', '401002', 'RX DE PARTES BLANDAS, LARINGE LATERAL, CAVUM RINOFARÍNGEO (RINOFARINX)'),
('RX', '401008', 'RX DE TÓRAX FRONTAL O LATERAL CON EQUIPO MÓVIL'),
('RX', '401009', 'RX DE TÓRAX SIMPLE FRONTAL O LATERAL'),
('RX', '401013', 'RX DE ABDOMEN SIMPLE'),
('RX', '401014', 'RX DE ABDOMEN SIMPLE, PROYECCIÓN COMPLEMENTARIA (LATERAL Y/O OBLICUA)'),
('RX', '401015', 'COLANGIOGRAFÍA INTRA O POSTOPERATORIA (POR SONDA T, O SIMILAR)'),
('RX', '401028', 'RX RENAL SIMPLE'),
('RX', '401029', 'RX VESICAL SIMPLE O PERIVESICAL'),
('RX', '401031', 'RX DE CPN, ÓRBITAS, ATM, HPN, MALAR, MAXILAR, ARCO CIGOMÁTICO Y CARA'),
('RX', '401032', 'RX DE CRÁNEO FRONTAL Y LATERAL'),
('RX', '401033', 'RX DE CRÁNEO PROYECCIÓN ESPECIAL DE BASE DE CRÁNEO (TOWNE)'),
('RX', '401035', 'RX DE OÍDO, UNILATERAL O BILATERAL'),
('RX', '401040', 'RX DE SILLA TURCA FRONTAL Y LATERAL'),
('RX', '401042', 'RX DE COLUMNA CERVICAL O ATLAS-AXIS (FRONTAL Y LATERAL)'),
('RX', '401043', 'RX DE COLUMNA CERVICAL (FRONTAL, LATERAL Y OBLICUAS)'),
('RX', '401044', 'RX DE COLUMNA CERVICAL FLEXIÓN Y EXTENSIÓN (DINÁMICAS)'),
('RX', '401045', 'RX DE COLUMNA DORSAL O DORSOLUMBAR LOCALIZADA, PARRILLA COSTAL ADULTOS (FRONTAL Y LATERAL)'),
('RX', '401046', 'RX DE COLUMNA LUMBAR O LUMBOSACRA (FRONTAL, LATERAL, 5° ESPACIO)'),
('RX', '401047', 'RX DE COLUMNA LUMBAR O LUMBOSACRA FLEXIÓN Y EXTENSIÓN (DINÁMICAS)'),
('RX', '401048', 'RX DE COLUMNA LUMBAR O LUMBOSACRA, OBLICUAS ADICIONALES'),
('RX', '401049', 'RX DE COLUMNA TOTAL, PANORÁMICA CON FOLIO GRADUADO FRONTAL O LATERAL'),
('RX', '401051', 'RX DE PELVIS, CADERA O COXOFEMORAL'),
('RX', '401052', 'RX DE PELVIS, CADERA O COXOFEMORAL, PROYECCIONES ESPECIALES'),
('RX', '401053', 'RX DE SACROCOXIS O ARTICULACIONES SACROILÍACAS'),
('RX', '401054', 'RX DE BRAZO, ANTEBRAZO, CODO, MUÑECA, MANO, DEDOS, PIE (FRONTAL Y LATERAL)'),
('RX', '401063', 'RX DE TÚNEL INTERCONDÍLEO O RADIO-CARPIANO'),
('RX', '401064', 'APOYO FLUOROSCÓPICO A PROCEDIMIENTOS INTRAOPERATORIOS'),
('RX', '401070', 'RX DE TÓRAX FRONTAL Y LATERAL'),
('RX', '401151', 'RX DE PELVIS, CADERA O COXOFEMORAL DE RN'),

('ECO', '404002', 'ECO OBSTÉTRICA'),
('ECO', '404003', 'ECO ABDOMINAL'),
('ECO', '404004', 'ECO COMO APOYO A CIRUGÍA'),
('ECO', '404005', 'ECO TRANSVAGINAL O TRANSRECTAL'),
('ECO', '404006', 'ECO GINECOLÓGICA, PELVIANA FEMENINA U OBSTÉTRICA CON ESTUDIO FETAL'),
('ECO', '404009', 'ECO PÉLVICA MASCULINA (INCLUYE VEJIGA Y PRÓSTATA)'),
('ECO', '404010', 'ECO RENAL (BILATERAL), O DE BAZO'),
('ECO', '404011', 'ECO ENCEFÁLICA (RN O LACTANTE)'),
('ECO', '404012', 'ECO ENCEFÁLICA (RN O LACTANTE)'),
('ECO', '404013', 'ECO OCULAR, UNILATERAL O BILATERAL'),
('ECO', '404014', 'ECO TESTICULAR (UNILATERAL O BILATERAL) (INCLUYE DOPPLER)'),
('ECO', '404015', 'ECO TIROIDEA (INCLUYE DOPPLER)'),
('ECO', '404016', 'ECO PARTES BLANDAS O MUSCULOESQUELÉTICA (CADA ZONA ANATÓMICA)'),
('ECO', '404017', 'ECO AXILAR'),
('ECO', '404019', 'ECO ESPINAL'),
('ECO', '404118', 'ECO VASCULAR (ARTERIAL Y VENOSA) PERIFÉRICA (BILATERAL)'),
('ECO', '404119', 'ECO DOPPLER DE VASOS DEL CUELLO'),
('ECO', '404120', 'ECO TRANSCRANEANA'),
('ECO', '404121', 'ECO ABDOMINAL O DE VASOS TESTICULARES'),
('ECO', '404122', 'ECO DOPPLER DE VASOS PLACENTARIOS'),
('ECO', '404218', 'ELASTOGRAFÍA HEPÁTICA');

-- ============================================
-- TABLA: examenes_especificos
-- ============================================
CREATE TABLE examenes_especificos (
    id SERIAL PRIMARY KEY,
    tipo_examen VARCHAR(10) NOT NULL CHECK (tipo_examen IN ('TAC', 'RX', 'ECO')),
    nombre VARCHAR(200) NOT NULL,
    activo BOOLEAN DEFAULT true,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(tipo_examen, nombre)
);

CREATE INDEX idx_examenes_especificos_tipo ON examenes_especificos(tipo_examen);

-- Datos de ejemplo (puedes eliminarlos o agregar los tuyos)
INSERT INTO examenes_especificos (tipo_examen, nombre) VALUES
-- TAC
('TAC', 'TAC DE CEREBRO SIN CONTRASTE'),
('TAC', 'TAC DE CEREBRO CON CONTRASTE'),
('TAC', 'TAC DE PERFUSIÓN CEREBRAL'),
('TAC', 'TAC DE SILLA TURCA (HIPOTÁLAMO HIPÓFISIS) SIN CONTRASTE'),
('TAC', 'TAC DE SILLA TURCA (HIPOTÁLAMO HIPÓFISIS) CON CONTRASTE'),
('TAC', 'TAC DE FOSA POSTERIOR SIN CONTRASTE'),
('TAC', 'TAC DE FOSA POSTERIOR CON CONTRASTE'),
('TAC', 'TAC DE OÍDO DER SIN CONTRASTE'),
('TAC', 'TAC DE OÍDO DER CON CONTRASTE'),
('TAC', 'TAC DE OÍDO IZQ SIN CONTRASTE'),
('TAC', 'TAC DE OÍDO IZQ CON CONTRASTE'),
('TAC', 'TAC DE OÍDOS SIN CONTRASTE'),
('TAC', 'TAC DE OÍDOS CON CONTRASTE'),
('TAC', 'TAC DE ÓRBITAS SIN CONTRASTE'),
('TAC', 'TAC DE ÓRBITAS CON CONTRASTE'),
('TAC', 'TAC DE ARTICULACIONES TEMPOROMANDIBULARES SIN CONTRASTE'),
('TAC', 'TAC DE ARTICULACIONES TEMPOROMANDIBULARES CON CONTRASTE'),
('TAC', 'TAC DE CAVIDADES PERINASALES SIN CONTRASTE'),
('TAC', 'TAC DE CAVIDADES PERINASALES CON CONTRASTE'),
('TAC', 'TAC DE MACIZO FACIAL SIN CONTRASTE'),
('TAC', 'TAC DE MACIZO FACIAL CON CONTRASTE'),
('TAC', 'TAC DE MANDÍBULA SIN CONTRASTE'),
('TAC', 'TAC DE MANDÍBULA CON CONTRASTE'),
('TAC', 'TAC DE COLUMNA CERVICAL SIN CONTRASTE'),
('TAC', 'TAC DE COLUMNA CERVICAL CON CONTRASTE'),
('TAC', 'TAC DE CUELLO (PARTES BLANDAS) SIN CONTRASTE'),
('TAC', 'TAC DE CUELLO (PARTES BLANDAS) CON CONTRASTE'),
('TAC', 'TAC DE CARA (PARTES BLANDAS) SIN CONTRASTE'),
('TAC', 'TAC DE CARA (PARTES BLANDAS) CON CONTRASTE'),
('TAC', 'TAC DE TÓRAX SIN CONTRASTE'),
('TAC', 'TAC DE TÓRAX CON CONTRASTE'),
('TAC', 'TAC DE ESTERNÓN SIN CONTRASTE'),
('TAC', 'TAC DE ESTERNÓN CON CONTRASTE'),
('TAC', 'TAC DE CLAVÍCULA DER SIN CONTRASTE'),
('TAC', 'TAC DE CLAVÍCULA DER CON CONTRASTE'),
('TAC', 'TAC DE CLAVÍCULA IZQ SIN CONTRASTE'),
('TAC', 'TAC DE CLAVÍCULA IZQ CON CONTRASTE'),
('TAC', 'TAC DE ARTICULACIÓN ACROMIOCLAVICULAR DER SIN CONTRASTE'),
('TAC', 'TAC DE ARTICULACIÓN ACROMIOCLAVICULAR DER CON CONTRASTE'),
('TAC', 'TAC DE ARTICULACIÓN ACROMIOCLAVICULAR IZQ SIN CONTRASTE'),
('TAC', 'TAC DE ARTICULACIÓN ACROMIOCLAVICULAR IZQ CON CONTRASTE'),
('TAC', 'TAC DE ESCÁPULA DER SIN CONTRASTE'),
('TAC', 'TAC DE ESCÁPULA DER CON CONTRASTE'),
('TAC', 'TAC DE ESCÁPULA IZQ SIN CONTRASTE'),
('TAC', 'TAC DE ESCÁPULA IZQ CON CONTRASTE'),
('TAC', 'TAC DE PARRILLA COSTAL SIN CONTRASTE'),
('TAC', 'TAC DE PARRILLA COSTAL CON CONTRASTE'),
('TAC', 'TAC DE ARTICULACIONES ESTERNOCLAVICULARES SIN CONTRASTE'),
('TAC', 'TAC DE ARTICULACIONES ESTERNOCLAVICULARES CON CONTRASTE'),
('TAC', 'TAC DE ABDOMEN SIN CONTRASTE'),
('TAC', 'TAC DE ABDOMEN CON CONTRASTE'),
('TAC', 'TAC DE PELVIS SIN CONTRASTE'),
('TAC', 'TAC DE PELVIS CON CONTRASTE'),
('TAC', 'TAC DE PELVIS ÓSEA SIN CONTRASTE'),
('TAC', 'TAC DE PELVIS ÓSEA CON CONTRASTE'),
('TAC', 'TAC DE COLUMNA SACROCOXIS SIN CONTRASTE'),
('TAC', 'TAC DE COLUMNA SACROCOXIS CON CONTRASTE'),
('TAC', 'TAC DE CADERA DER SIN CONTRASTE'),
('TAC', 'TAC DE CADERA DER CON CONTRASTE'),
('TAC', 'TAC DE CADERA IZQ SIN CONTRASTE'),
('TAC', 'TAC DE CADERA IZQ CON CONTRASTE'),
('TAC', 'TAC DE CADERAS SIN CONTRASTE'),
('TAC', 'TAC DE CADERAS CON CONTRASTE'),
('TAC', 'TAC DE ARTICULACIONES SACROILÍACAS SIN CONTRASTE'),
('TAC', 'TAC DE ARTICULACIONES SACROILÍACAS CON CONTRASTE'),
('TAC', 'TAC DE MUSLO (FÉMUR) DER SIN CONTRASTE'),
('TAC', 'TAC DE MUSLO (FÉMUR) DER CON CONTRASTE'),
('TAC', 'TAC DE MUSLO (FÉMUR) IZQ SIN CONTRASTE'),
('TAC', 'TAC DE MUSLO (FÉMUR) IZQ CON CONTRASTE'),
('TAC', 'TAC DE RODILLA DER SIN CONTRASTE'),
('TAC', 'TAC DE RODILLA DER CON CONTRASTE'),
('TAC', 'TAC DE RODILLA IZQ SIN CONTRASTE'),
('TAC', 'TAC DE RODILLA IZQ CON CONTRASTE'),
('TAC', 'TAC DE RODILLAS SIN CONTRASTE'),
('TAC', 'TAC DE RODILLAS CON CONTRASTE'),
('TAC', 'TAC DE RÓTULAS'),
('TAC', 'TAC DE PIERNA (TIBIA Y PERONÉ) DER SIN CONTRASTE'),
('TAC', 'TAC DE PIERNA (TIBIA Y PERONÉ) DER CON CONTRASTE'),
('TAC', 'TAC DE PIERNA (TIBIA Y PERONÉ) IZQ SIN CONTRASTE'),
('TAC', 'TAC DE PIERNA (TIBIA Y PERONÉ) IZQ CON CONTRASTE'),
('TAC', 'TAC DE TOBILLO DER SIN CONTRASTE'),
('TAC', 'TAC DE TOBILLO DER CON CONTRASTE'),
('TAC', 'TAC DE TOBILLO IZQ SIN CONTRASTE'),
('TAC', 'TAC DE TOBILLO IZQ CON CONTRASTE'),
('TAC', 'TAC DE PIE DER SIN CONTRASTE'),
('TAC', 'TAC DE PIE DER CON CONTRASTE'),
('TAC', 'TAC DE PIE IZQ SIN CONTRASTE'),
('TAC', 'TAC DE PIE IZQ CON CONTRASTE'),
('TAC', 'TAC DE CALCÁNEO DER SIN CONTRASTE'),
('TAC', 'TAC DE CALCÁNEO DER CON CONTRASTE'),
('TAC', 'TAC DE CALCÁNEO IZQ SIN CONTRASTE'),
('TAC', 'TAC DE CALCÁNEO IZQ CON CONTRASTE'),
('TAC', 'TAC DE HOMBRO DER SIN CONTRASTE'),
('TAC', 'TAC DE HOMBRO DER CON CONTRASTE'),
('TAC', 'TAC DE HOMBRO IZQ SIN CONTRASTE'),
('TAC', 'TAC DE HOMBRO IZQ CON CONTRASTE'),
('TAC', 'TAC DE BRAZO (HÚMERO) DER SIN CONTRASTE'),
('TAC', 'TAC DE BRAZO (HÚMERO) DER CON CONTRASTE'),
('TAC', 'TAC DE BRAZO (HÚMERO) IZQ SIN CONTRASTE'),
('TAC', 'TAC DE BRAZO (HÚMERO) IZQ CON CONTRASTE'),
('TAC', 'TAC DE CODO DER SIN CONTRASTE'),
('TAC', 'TAC DE CODO DER CON CONTRASTE'),
('TAC', 'TAC DE CODO IZQ SIN CONTRASTE'),
('TAC', 'TAC DE CODO IZQ CON CONTRASTE'),
('TAC', 'TAC DE ANTEBRAZO DER SIN CONTRASTE'),
('TAC', 'TAC DE ANTEBRAZO DER CON CONTRASTE'),
('TAC', 'TAC DE ANTEBRAZO IZQ SIN CONTRASTE'),
('TAC', 'TAC DE ANTEBRAZO IZQ CON CONTRASTE'),
('TAC', 'TAC DE MUÑECA DER SIN CONTRASTE'),
('TAC', 'TAC DE MUÑECA DER CON CONTRASTE'),
('TAC', 'TAC DE MUÑECA IZQ SIN CONTRASTE'),
('TAC', 'TAC DE MUÑECA IZQ CON CONTRASTE'),
('TAC', 'TAC DE ESCAFOIDES DER SIN CONTRASTE'),
('TAC', 'TAC DE ESCAFOIDES DER CON CONTRASTE'),
('TAC', 'TAC DE ESCAFOIDES IZQ SIN CONTRASTE'),
('TAC', 'TAC DE ESCAFOIDES IZQ CON CONTRASTE'),
('TAC', 'TAC DE MANO DER SIN CONTRASTE'),
('TAC', 'TAC DE MANO DER CON CONTRASTE'),
('TAC', 'TAC DE MANO IZQ SIN CONTRASTE'),
('TAC', 'TAC DE MANO IZQ CON CONTRASTE'),
('TAC', 'TAC DE COLUMNA DORSAL SIN CONTRASTE'),
('TAC', 'TAC DE COLUMNA DORSAL CON CONTRASTE'),
('TAC', 'TAC DE COLUMNA LUMBAR SIN CONTRASTE'),
('TAC', 'TAC DE COLUMNA LUMBAR CON CONTRASTE'),
('TAC', 'TAC DE ABDOMEN Y PELVIS SIN CONTRASTE'),
('TAC', 'TAC DE ABDOMEN Y PELVIS CON CONTRASTE'),
('TAC', 'PIELOTAC'),
('TAC', 'UROTAC'),
('TAC', 'CISTOGRAFÍA POR TAC'),
('TAC', 'TAC DE COLONOSCOPÍA VIRTUAL'),
('TAC', 'TAC DE PLANIFICACIÓN DE RADIOTERAPIA'),
('TAC', 'BIOPSIA BAJO TAC'),
('TAC', 'DRENAJE PERCUTÁNEO BAJO TAC'),
('TAC', 'TAC DE SCORE DE CALCIO CORONARIO'),
('TAC', 'ENTEROGRAFÍA POR TAC (SIN SONDA)'),
('TAC', 'ENTEROGRAFÍA POR TAC (CON SONDA)'),
('TAC', 'ANGIOTAC DE CEREBRO'),
('TAC', 'ANGIOTAC DE TÓRAX'),
('TAC', 'ANGIOTAC DE ABDOMEN'),
('TAC', 'ANGIOTAC DE ARTERIAS RENALES'),
('TAC', 'ANGIOTAC DE CUELLO'),
('TAC', 'ANGIOTAC DE PELVIS'),
('TAC', 'ANGIOTAC DE CORAZÓN'),
('TAC', 'ANGIOTAC DE ARTERIAS CORONARIAS'),
('TAC', 'ANGIOTAC DE EXTREMIDADES INFERIORES'),
('TAC', 'ANGIOTAC DE EXTREMIDAD INFERIOR DER'),
('TAC', 'ANGIOTAC DE EXTREMIDAD INFERIOR IZQ'),
('TAC', 'ANGIOTAC DE EXTREMIDAD SUPERIOR DER'),
('TAC', 'ANGIOTAC DE EXTREMIDAD SUPERIOR IZQ'),

-- RX
('RX', 'RX DE CÁVUM RINOFARÍNGEO BOCA ABIERTA Y CERRADA'),
('RX', 'RX DE LARINGE LATERAL (PARTES BLANDAS)'),
('RX', 'RX DE TÓRAX OBLICUAS'),
('RX', 'RX DE TÓRAX DECÚBITO FRONTAL RAYO HORIZONTAL'),
('RX', 'RX DE TÓRAX DECÚBITO LATERAL RAYO HORIZONTAL'),
('RX', 'RX DE TÓRAX FRONTAL PORTÁTIL'),
('RX', 'RX DE TÓRAX LATERAL PORTÁTIL'),
('RX', 'RX DE TÓRAX FRONTAL'),
('RX', 'RX DE TÓRAX LATERAL'),
('RX', 'RX DE ABDOMEN FRONTAL'),
('RX', 'RX DE ABDOMEN FRONTAL PORTÁTIL'),
('RX', 'RX DE ABDOMEN LATERAL'),
('RX', 'RX DE ABDOMEN DECÚBITO LATERAL CON RAYO HORIZONTAL'),
('RX', 'COLANGIOGRAFÍA POR SONDA T O SIMILAR'),
('RX', 'RX RENAL'),
('RX', 'RX VESICAL'),
('RX', 'RX DE CAVIDADES PERINASALES'),
('RX', 'RX DE ÓRBITA DER'),
('RX', 'RX DE ÓRBITA IZQ'),
('RX', 'RX DE ARTICULACIÓN TEMPOROMANDIBULAR DER'),
('RX', 'RX DE ARTICULACIÓN TEMPOROMANDIBULAR IZQ'),
('RX', 'RX DE MANDÍBULA'),
('RX', 'RX DE HUESOS PROPIOS DE LA NARIZ'),
('RX', 'RX DE MALAR DER'),
('RX', 'RX DE MALAR IZQ'),
('RX', 'RX DE ARCO CIGOMÁTICO DER'),
('RX', 'RX DE ARCO CIGOMÁTICO IZQ'),
('RX', 'RX DE CRÁNEO FRONTAL Y LATERAL'),
('RX', 'RX DE CRÁNEO WATERS'),
('RX', 'RX DE CRÁNEO CALDWELL'),
('RX', 'RX DE CRÁNEO TOWNE'),
('RX', 'RX DE BASE DE CRÁNEO'),
('RX', 'RX DE SILLA TURCA FRONTAL Y LATERAL'),
('RX', 'RX DE COLUMNA CERVICAL FRONTAL Y LATERAL'),
('RX', 'RX DE COLUMNA ATLAS-AXIS'),
('RX', 'RX DE COLUMNA CERVICAL FRONTAL, LATERAL Y OBLICUAS'),
('RX', 'RX DE COLUMNA CERVICAL OBLICUAS'),
('RX', 'RX DE COLUMNA CERVICAL FLEXIÓN Y EXTENSIÓN (DINÁMICAS)'),
('RX', 'RX DE COLUMNA DORSAL FRONTAL Y LATERAL'),
('RX', 'RX DE COLUMNA DORSOLUMBAR FRONTAL Y LATERAL (FOCALIZADA)'),
('RX', 'RX DE COLUMNA DORSAL FLEXIÓN Y EXTENSIÓN (DINÁMICAS)'),
('RX', 'RX DE PARRILLA COSTAL DER FRONTAL Y OBLICUA'),
('RX', 'RX DE PARRILLA COSTAL IZQ FRONTAL Y OBLICUA'),
('RX', 'RX DE COLUMNA LUMBAR FRONTAL Y LATERAL'),
('RX', 'RX DE COLUMNA LUMBAR FRONTAL, LATERAL Y FOCALIZADA 5.º ESPACIO'),
('RX', 'RX DE COLUMNA LUMBAR FLEXIÓN Y EXTENSIÓN (DINÁMICAS)'),
('RX', 'RX DE COLUMNA LUMBAR OBLICUAS'),
('RX', 'RX DE COLUMNA TOTAL FRONTAL'),
('RX', 'RX DE COLUMNA TOTAL LATERAL'),
('RX', 'RX DE COLUMNA TOTAL FRONTAL CON TEST DE BENDING'),
('RX', 'RX DE EEII'),
('RX', 'RX DE PELVIS FRONTAL'),
('RX', 'RX DE PELVIS FRONTAL DE PIE'),
('RX', 'RX DE CADERA DER FRONTAL'),
('RX', 'RX DE CADERA IZQ FRONTAL'),
('RX', 'RX DE CADERA DER AXIAL'),
('RX', 'RX DE CADERA IZQ AXIAL'),
('RX', 'RX DE CADERA DER ALAR'),
('RX', 'RX DE CADERA IZQ ALAR'),
('RX', 'RX DE CADERA DER OBTURATRIZ'),
('RX', 'RX DE CADERA IZQ OBTURATRIZ'),
('RX', 'RX DE CADERA DER CROSSTABLE'),
('RX', 'RX DE CADERA IZQ CROSSTABLE'),
('RX', 'RX DE CADERA DER DUNN'),
('RX', 'RX DE CADERA IZQ DUNN'),
('RX', 'RX DE CADERA DER LOWENSTEIN'),
('RX', 'RX DE CADERA IZQ LOWENSTEIN'),
('RX', 'RX DE PELVIS LOWENSTEIN'),
('RX', 'RX DE PELVIS EN ABDUCCIÓN'),
('RX', 'RX DE PELVIS INLET'),
('RX', 'RX DE PELVIS OUTLET'),
('RX', 'RX DE SACROCOXIS FRONTAL Y LATERAL'),
('RX', 'RX DE SACRO FRONTAL Y LATERAL'),
('RX', 'RX DE COXIS FRONTAL Y LATERAL'),
('RX', 'RX DE ARTICULACIONES SACROILÍACAS'),
('RX', 'RX DE TÓRAX FRONTAL Y LATERAL'),
('RX', 'RX DE PELVIS DE RN O MENOR DE 6 AÑOS'),
-- ECO
('ECO', 'ECO OBSTÉTRICA'),
('ECO', 'ECO ABDOMINAL'),
('ECO', 'ECO APOYO A CIRUGÍA O PROCEDIMIENTO'),
('ECO', 'ECO TRANSVAGINAL'),
('ECO', 'ECO TRANSRECTAL'),
('ECO', 'ECO PÉLVICA FEMENINA'),
('ECO', 'ECO PÉLVICA MASCULINA (VEJIGA Y PRÓSTATA)'),
('ECO', 'ECO RENAL'),
('ECO', 'ECO ENCEFÁLICA'),
('ECO', 'ECO MAMARIA BILATERAL'),
('ECO', 'ECO MAMARIA UNILATERAL DER'),
('ECO', 'ECO MAMARIA UNILATERAL IZQ'),
('ECO', 'ECO OCULAR DER'),
('ECO', 'ECO OCULAR IZQ'),
('ECO', 'ECO OCULAR BILATERAL'),
('ECO', 'ECO TESTICULAR DER'),
('ECO', 'ECO TESTICULAR IZQ'),
('ECO', 'ECO TESTICULAR BILATERAL'),
('ECO', 'ECO TIROIDEA'),
('ECO', 'ECO PARTES BLANDAS DE PARED ABDOMINAL'),
('ECO', 'ECO PARTES BLANDAS DE REGIÓN INGUINAL DER'),
('ECO', 'ECO PARTES BLANDAS DE REGIÓN INGUINAL IZQ'),
('ECO', 'ECO PARTES BLANDAS DE HOMBRO DER'),
('ECO', 'ECO PARTES BLANDAS DE HOMBRO IZQ'),
('ECO', 'ECO PARTES BLANDAS DE BRAZO DER'),
('ECO', 'ECO PARTES BLANDAS DE BRAZO IZQ'),
('ECO', 'ECO PARTES BLANDAS DE CODO DER'),
('ECO', 'ECO PARTES BLANDAS DE CODO IZQ'),
('ECO', 'ECO PARTES BLANDAS DE ANTEBRAZO DER'),
('ECO', 'ECO PARTES BLANDAS DE ANTEBRAZO IZQ'),
('ECO', 'ECO PARTES BLANDAS DE MUÑECA DER'),
('ECO', 'ECO PARTES BLANDAS DE MUÑECA IZQ'),
('ECO', 'ECO PARTES BLANDAS DE MANO DER'),
('ECO', 'ECO PARTES BLANDAS DE MANO IZQ'),
('ECO', 'ECO PARTES BLANDAS DE DEDO PULGAR DER'),
('ECO', 'ECO PARTES BLANDAS DE DEDO PULGAR IZQ'),
('ECO', 'ECO PARTES BLANDAS DE DEDO ÍNDICE DER'),
('ECO', 'ECO PARTES BLANDAS DE DEDO ÍNDICE IZQ'),
('ECO', 'ECO PARTES BLANDAS DE DEDO MEDIO DER'),
('ECO', 'ECO PARTES BLANDAS DE DEDO MEDIO IZQ'),
('ECO', 'ECO PARTES BLANDAS DE DEDO ANULAR DER'),
('ECO', 'ECO PARTES BLANDAS DE DEDO ANULAR IZQ'),
('ECO', 'ECO PARTES BLANDAS DE DEDO MEÑIQUE DER'),
('ECO', 'ECO PARTES BLANDAS DE DEDO MEÑIQUE IZQ'),
('ECO', 'ECO PARTES BLANDAS DE GLÚTEO DER'),
('ECO', 'ECO PARTES BLANDAS DE GLÚTEO IZQ'),
('ECO', 'ECO PARTES BLANDAS DE CADERA DER'),
('ECO', 'ECO PARTES BLANDAS DE CADERA IZQ'),
('ECO', 'ECO PARTES BLANDAS DE MUSLO DER'),
('ECO', 'ECO PARTES BLANDAS DE MUSLO IZQ'),
('ECO', 'ECO PARTES BLANDAS DE RODILLA DER'),
('ECO', 'ECO PARTES BLANDAS DE RODILLA IZQ'),
('ECO', 'ECO PARTES BLANDAS DE PIERNA DER'),
('ECO', 'ECO PARTES BLANDAS DE PIERNA IZQ'),
('ECO', 'ECO PARTES BLANDAS DE TOBILLO DER'),
('ECO', 'ECO PARTES BLANDAS DE TOBILLO IZQ'),
('ECO', 'ECO PARTES BLANDAS DE PIE DER'),
('ECO', 'ECO PARTES BLANDAS DE PIE IZQ'),
('ECO', 'ECO PARTES BLANDAS DE PRIMER ORTEJO DER'),
('ECO', 'ECO PARTES BLANDAS DE PRIMER ORTEJO IZQ'),
('ECO', 'ECO PARTES BLANDAS DE SEGUNDO ORTEJO DER'),
('ECO', 'ECO PARTES BLANDAS DE SEGUNDO ORTEJO IZQ'),
('ECO', 'ECO PARTES BLANDAS DE TERCER ORTEJO DER'),
('ECO', 'ECO PARTES BLANDAS DE TERCER ORTEJO IZQ'),
('ECO', 'ECO PARTES BLANDAS DE CUARTO ORTEJO DER'),
('ECO', 'ECO PARTES BLANDAS DE CUARTO ORTEJO IZQ'),
('ECO', 'ECO PARTES BLANDAS DE QUINTO ORTEJO DER'),
('ECO', 'ECO PARTES BLANDAS DE QUINTO ORTEJO IZQ'),
('ECO', 'ECO PARTES BLANDAS DE REGIÓN CERVICAL'),
('ECO', 'ECO PARTES BLANDAS DE REGIÓN DORSAL'),
('ECO', 'ECO PARTES BLANDAS DE REGIÓN LUMBAR'),
('ECO', 'ECO PARTES BLANDAS DE REGIÓN FACIAL'),
('ECO', 'ECO PARTES BLANDAS DE GLÁNDULAS SALIVALES'),
('ECO', 'ECO PARTES BLANDAS DE REGIÓN CRANEAL'),
('ECO', 'ECO PARTES BLANDAS DE REGIÓN PECTORAL'),
('ECO', 'ECO PARTES BLANDAS DE REGIÓN COSTAL'),
('ECO', 'ECO PARTES BLANDAS DE REGIÓN AURICULAR DER'),
('ECO', 'ECO PARTES BLANDAS DE REGIÓN AURICULAR IZQ'),
('ECO', 'ECO PARTES BLANDAS DE PENE'),
('ECO', 'ECO MUSCULOESQUELÉTICA DE HOMBRO DER'),
('ECO', 'ECO MUSCULOESQUELÉTICA DE HOMBRO IZQ'),
('ECO', 'ECO MUSCULOESQUELÉTICA DE CODO DER'),
('ECO', 'ECO MUSCULOESQUELÉTICA DE CODO IZQ'),
('ECO', 'ECO MUSCULOESQUELÉTICA DE MUÑECA DER'),
('ECO', 'ECO MUSCULOESQUELÉTICA DE MUÑECA IZQ'),
('ECO', 'ECO MUSCULOESQUELÉTICA DE MANO DER'),
('ECO', 'ECO MUSCULOESQUELÉTICA DE MANO IZQ'),
('ECO', 'ECO MUSCULOESQUELÉTICA DE DEDO PULGAR DER'),
('ECO', 'ECO MUSCULOESQUELÉTICA DE DEDO PULGAR IZQ'),
('ECO', 'ECO MUSCULOESQUELÉTICA DE DEDO ÍNDICE DER'),
('ECO', 'ECO MUSCULOESQUELÉTICA DE DEDO ÍNDICE IZQ'),
('ECO', 'ECO MUSCULOESQUELÉTICA DE DEDO MEDIO DER'),
('ECO', 'ECO MUSCULOESQUELÉTICA DE DEDO MEDIO IZQ'),
('ECO', 'ECO MUSCULOESQUELÉTICA DE DEDO ANULAR DER'),
('ECO', 'ECO MUSCULOESQUELÉTICA DE DEDO ANULAR IZQ'),
('ECO', 'ECO MUSCULOESQUELÉTICA DE DEDO MEÑIQUE DER'),
('ECO', 'ECO MUSCULOESQUELÉTICA DE DEDO MEÑIQUE IZQ'),
('ECO', 'ECO MUSCULOESQUELÉTICA DE CADERA DER'),
('ECO', 'ECO MUSCULOESQUELÉTICA DE CADERA IZQ'),
('ECO', 'ECO MUSCULOESQUELÉTICA DE RODILLA DER'),
('ECO', 'ECO MUSCULOESQUELÉTICA DE RODILLA IZQ'),
('ECO', 'ECO MUSCULOESQUELÉTICA DE PIERNA DER'),
('ECO', 'ECO MUSCULOESQUELÉTICA DE TOBILLO IZQ'),
('ECO', 'ECO MUSCULOESQUELÉTICA DE PIE DER'),
('ECO', 'ECO MUSCULOESQUELÉTICA DE PIE IZQ'),
('ECO', 'ECO MUSCULOESQUELÉTICA DE PRIMER ORTEJO DER'),
('ECO', 'ECO MUSCULOESQUELÉTICA DE PRIMER ORTEJO IZQ'),
('ECO', 'ECO MUSCULOESQUELÉTICA DE SEGUNDO ORTEJO DER'),
('ECO', 'ECO MUSCULOESQUELÉTICA DE SEGUNDO ORTEJO IZQ'),
('ECO', 'ECO MUSCULOESQUELÉTICA DE TERCER ORTEJO DER'),
('ECO', 'ECO MUSCULOESQUELÉTICA DE TERCER ORTEJO IZQ'),
('ECO', 'ECO MUSCULOESQUELÉTICA DE CUARTO ORTEJO DER'),
('ECO', 'ECO MUSCULOESQUELÉTICA DE CUARTO ORTEJO IZQ'),
('ECO', 'ECO MUSCULOESQUELÉTICA DE QUINTO ORTEJO DER'),
('ECO', 'ECO MUSCULOESQUELÉTICA DE QUINTO ORTEJO IZQ'),
('ECO', 'ECO AXILAR DER'),
('ECO', 'ECO AXILAR IZQ'),
('ECO', 'ECO ESPINAL'),
('ECO', 'ECO DOPPLER ARTERIAL EXTREMIDAD INFERIOR DER'),
('ECO', 'ECO DOPPLER ARTERIAL EXTREMIDAD INFERIOR IZQ'),
('ECO', 'ECO DOPPLER ARTERIAL EXTREMIDAD INFERIOR BILATERAL'),
('ECO', 'ECO DOPPLER VENOSO EXTREMIDAD INFERIOR DER'),
('ECO', 'ECO DOPPLER VENOSO EXTREMIDAD INFERIOR IZQ'),
('ECO', 'ECO DOPPLER VENOSO EXTREMIDAD INFERIOR BILATERAL'),
('ECO', 'ECO DOPPLER ARTERIAL EXTREMIDAD SUPERIOR DER'),
('ECO', 'ECO DOPPLER ARTERIAL EXTREMIDAD SUPERIOR IZQ'),
('ECO', 'ECO DOPPLER ARTERIAL EXTREMIDAD SUPERIOR BILATERAL'),
('ECO', 'ECO DOPPLER VENOSO EXTREMIDAD SUPERIOR DER'),
('ECO', 'ECO DOPPLER VENOSO EXTREMIDAD SUPERIOR IZQ'),
('ECO', 'ECO DOPPLER VENOSO EXTREMIDAD SUPERIOR BILATERAL'),
('ECO', 'ECO DOPPLER MAPEO VENOSO EXTREMIDAD INFERIOR'),
('ECO', 'ECO DOPPLER MAPEO VENOSO EXTREMIDAD SUPERIOR'),
('ECO', 'ECO DOPPLER VASOS DEL CUELLO'),
('ECO', 'ECO DOPPLER TRANSCRANEANA'),
('ECO', 'ECO DOPPLER ABDOMINAL'),
('ECO', 'ECO DOPPLER PORTAL'),
('ECO', 'ECO DOPPLER RENAL'),
('ECO', 'ECO DOPPLER TESTICULAR'),
('ECO', 'ECO DOPPLER DE PENE'),
('ECO', 'ECO DOPPLER VASOS PLACENTARIOS'),
('ECO', 'ELASTOGRAFÍA HEPÁTICA');

-- Protocolos TAC
--CREATE TABLE protocolos_tac (
--    id SERIAL PRIMARY KEY,
--    nombre VARCHAR(150) UNIQUE NOT NULL,
--    activo BOOLEAN DEFAULT true
--);

-- Diagnosticos
CREATE TABLE diagnosticos (
    id SERIAL PRIMARY KEY,
    nombre TEXT UNIQUE NOT NULL,
    activo BOOLEAN DEFAULT true
);

-- Personal Medico
CREATE TABLE personal_medico (
    id SERIAL PRIMARY KEY,
    nombre VARCHAR(150) NOT NULL,
    tipo VARCHAR(50) NOT NULL CHECK (tipo IN ('TM', 'TP', 'MEDICO', 'SECRETARIA', 'GENERAL')),
    activo BOOLEAN DEFAULT true
);

CREATE INDEX idx_personal_tipo ON personal_medico(tipo);

-- ============================================
-- TABLA: examenes_base (datos comunes)
-- ============================================
CREATE TABLE examenes_base (
    id SERIAL PRIMARY KEY,
    tipo_examen VARCHAR(10) NOT NULL CHECK (tipo_examen IN ('TAC', 'RX', 'ECO')),
    
    -- Datos comunes
    fecha_realizacion DATE NOT NULL,
    atencion VARCHAR(20) NOT NULL CHECK (atencion IN ('Abierta', 'Cerrada', 'Urgencia')),
    prevision_id INTEGER REFERENCES previsiones(id),
    procedencia_id INTEGER REFERENCES procedencias(id),
    paciente_id INTEGER NOT NULL REFERENCES pacientes(id),
    examen_especifico_id INTEGER NOT NULL REFERENCES examenes_especificos(id),
    codigo_mai_id INTEGER REFERENCES codigos_mai(id),
    contrato VARCHAR(50) CHECK (contrato IN ('Empresa Externa', 'Institucional')),
    
    -- Auditoria
    mes_realizacion INTEGER NOT NULL,  -- 1-12
    anio_realizacion INTEGER NOT NULL,
    created_by INTEGER REFERENCES usuarios(id),
    updated_by INTEGER REFERENCES usuarios(id),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL,
    en_revision BOOLEAN DEFAULT false,
    motivo_revision TEXT NULL
);

CREATE INDEX idx_examenes_fecha ON examenes_base(fecha_realizacion);
CREATE INDEX idx_examenes_tipo ON examenes_base(tipo_examen);
CREATE INDEX idx_examenes_paciente ON examenes_base(paciente_id);
CREATE INDEX idx_examenes_mes_anio ON examenes_base(mes_realizacion, anio_realizacion);
CREATE INDEX idx_examenes_especificos ON examenes_base(examen_especifico_id);

-- ============================================
-- TABLA: examenes_tac
-- ============================================
CREATE TABLE examenes_tac (
    id SERIAL PRIMARY KEY,
    examen_base_id INTEGER UNIQUE NOT NULL REFERENCES examenes_base(id) ON DELETE CASCADE,
    
    -- Datos especificos TAC
    fecha_solicitud DATE NOT NULL,
    hora_realizacion TIME NOT NULL,
    fecha_nacimiento DATE,
    edad INTEGER,  -- Calculado automaticamente
    externo VARCHAR(50),  -- Opcional: Ambulatorio/Hospitalizado/Urgencias
--    protocolo_id INTEGER REFERENCES protocolos_tac(id),
    cod_acv BOOLEAN NOT NULL,
    ges BOOLEAN NOT NULL,
    medio_contraste BOOLEAN NOT NULL,
    vfge VARCHAR(50),  -- Sin Creatinina o valor numerico, opcional
    premedicado BOOLEAN,  -- Obligatorio si vfge tiene valor
    diagnostico_clinico_id INTEGER REFERENCES diagnosticos(id),
    medico_solicitante_id INTEGER REFERENCES personal_medico(id),
    tm_id INTEGER REFERENCES personal_medico(id),
    tp_id INTEGER REFERENCES personal_medico(id),
    secretaria_id INTEGER REFERENCES personal_medico(id),
    observacion TEXT
);

CREATE INDEX idx_tac_examen ON examenes_tac(examen_base_id);

-- ============================================
-- TABLA: examenes_rx
-- ============================================
CREATE TABLE examenes_rx (
    id SERIAL PRIMARY KEY,
    examen_base_id INTEGER UNIQUE NOT NULL REFERENCES examenes_base(id) ON DELETE CASCADE,
    
    -- Datos especificos RX
    hora_realizacion TIME NOT NULL,
    tm_tp_id INTEGER REFERENCES personal_medico(id)  -- Puede ser TM o TP
);

CREATE INDEX idx_rx_examen ON examenes_rx(examen_base_id);

-- ============================================
-- TABLA: examenes_eco
-- ============================================
CREATE TABLE examenes_eco (
    id SERIAL PRIMARY KEY,
    examen_base_id INTEGER UNIQUE NOT NULL REFERENCES examenes_base(id) ON DELETE CASCADE,
    
    -- Datos especificos ECO
    diagnostico_id INTEGER REFERENCES diagnosticos(id),
    realizado_id INTEGER REFERENCES personal_medico(id),
    transcribe_id INTEGER REFERENCES personal_medico(id)
);

CREATE INDEX idx_eco_examen ON examenes_eco(examen_base_id);

-- ============================================
-- TRIGGERS para updated_at
-- ============================================
CREATE OR REPLACE FUNCTION update_timestamp()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_usuarios_updated
BEFORE UPDATE ON usuarios
FOR EACH ROW EXECUTE FUNCTION update_timestamp();

CREATE TRIGGER trigger_pacientes_updated
BEFORE UPDATE ON pacientes
FOR EACH ROW EXECUTE FUNCTION update_timestamp();

CREATE TRIGGER trigger_examenes_updated
BEFORE UPDATE ON examenes_base
FOR EACH ROW EXECUTE FUNCTION update_timestamp();

-- ============================================
-- FUNCION: Calcular edad automaticamente
-- ============================================
CREATE OR REPLACE FUNCTION calcular_edad(fecha_nac DATE, fecha_ref DATE)
RETURNS INTEGER AS $$
BEGIN
    RETURN EXTRACT(YEAR FROM AGE(fecha_ref, fecha_nac));
END;
$$ LANGUAGE plpgsql;

-- ============================================
-- DATOS INICIALES DE PRUEBA (BORRAR)
-- ============================================

-- Usuario administrador de prueba
--INSERT INTO usuarios (rut, nombre, email, password_hash, rol)
--VALUES ('12345678-9', 'Admin Prueba', 'admin@hospital.cl', '$2b$12$LQv3c1yqBWVHxkd0LHAkCOYz6TtxMQJqhN8/LewY5cOW3G9WQ7W4m', 'administrador');
-- Password: admin123

-- Usuario ingresador de prueba
--INSERT INTO usuarios (rut, nombre, email, password_hash, rol)
--VALUES ('98765432-1', 'Tecnologo Prueba', 'tecnologo@hospital.cl', '$2b$12$LQv3c1yqBWVHxkd0LHAkCOYz6TtxMQJqhN8/LewY5cOW3G9WQ7W4m', 'ingresador');
-- Password: admin123

-- Paciente de prueba
--INSERT INTO pacientes (rut, nombre_completo, fecha_nacimiento)
--VALUES ('11111111-1', 'Juan Perez Gonzalez', '1980-05-15');

-- Procedencias comunes
--INSERT INTO procedencias (nombre) VALUES
--('Consulta Externa'),
--('Urgencias'),
--('Hospitalizacion'),
--('UPC'),
--('Pabellon');

-- Verificacion
SELECT 'Base de datos creada exitosamente' AS status;
SELECT COUNT(*) AS total_tablas FROM information_schema.tables WHERE table_schema = 'public';
CREATE INDEX idx_examenes_revision ON examenes_base(en_revision) WHERE en_revision = true;